### ISSUE TITLE
Unable to accept invites using 3.9.0 Beta 1

### ISSUE THREAD

**Issue by bren-m** [Ericsson/exchangecalendar#542]
Exchange calendar version: 3.9.0 Beta 1
Lightning version: 4.7.5
Thunderbird version: 45.5.0
OS X version: 10.12.1

As per the title, after upgrading to 3.9.0 Beta 1 I can't accept invites. I click on Accept or Accept All and nothing happens. I had to roll back to 3.8.0

**Comment by rainerklier** [comment]
i can confirm.
this also affects me.
Lightning version: 4.7.5
Thunderbird version: 45.5.0
Linux, openSUSE Tumbleweed x86_64

**Comment by peshane** [comment]
i can confirm too
lightening v4.7.4
thunderbird v45.5.0
archlinux up to date

**Comment by nobwyn** [comment]
the same with:

Exchange EWS Provider 3.9.0-beta1
Lightning 4.7.4
Thunderbird 45.4.0
Sabayon Linux amd64 16.12

**Comment by bavincen** [comment]
please chck this in recent version and close

**Comment by bren-m** [comment]
The issue still exists in the 3.9.0 full release i.e. I can't accept meetings. 

This is not fixed.

Exchange Calendar: 3.9.0
Lightning: 4.7.6
Thunderbird: 45.6.0
Mac OS: 10.12.2

**Comment by aleskovets** [comment]
Same here.
Exchange Calendar: 3.9.0
Lightning: 4.7.4
Thunderbird 45.5.1

**Comment by laerm** [comment]
Same for me.
Exchange Calendar: 3.9.0
Lightning: 4.7.4
Thunderbird: 45.5.1
Ubuntu: 16.04 LTS

**Comment by steinisv** [comment]
Same here.
Exchange EWS Provider 3.9.0
Lighting 4.7.6
Thunderbird 45.6.0

**Comment by mattconway1984** [comment]
Same problem for me.
Exchange EWS Provider 3.9.0
Lightning 4.7.4
Thunderbird 45.6.0

Accept invitation does not work - if I click "I will attend" the popup shows to send a response or not... Doesn't matter what option I choose, the attendance is not recorded (Also note: if I select "send the response now", no response is sent).

Earlier versions of this plugin were working fine for me (been using it about 2 years).

**Comment by xarli64** [comment]
Same problem here.

Exchange EWS Provider 3.9.0
Lightning 4.7.4
Thunderbird 45.5.1 (Ubuntu 16.10 package)

**Comment by cratoo** [comment]
Same problem for me too:
Console tells me:
`exchangecalendar@extensions.1st-setup.nl/interfaces/exchangeCalendar/mivExchangeCalendar.js, line 5573: TypeError: proposeStart.getInTimezone is not a function`

**Comment by smares** [comment]
I get a different error when I try to send the answer that I will attend a meeting:

> Timestamp: 26.01.2017 10:44:09
> Warning: ReferenceError: reference to undefined property this._id
> Source File: resource://interfaces/exchangeBaseItem/mivExchangeBaseItem.js
> Line: 808

> Timestamp: 26.01.2017 10:44:09
> Warning: ReferenceError: reference to undefined property this._exchangeXML
> Source File: resource://interfaces/exchangeBaseItem/mivExchangeBaseItem.js
> Line: 2990

Thunderbird 45.5.1 under Ubuntu 16.04 LTE
Lightning 4.7.4
Exchange EWS Provider 3.9.0 (final)

**Comment by ogjerstad** [comment]
I get no errors in the log, but it doesn't work still. Is there anything we can do to help debug this? Server is Exchange 2010, btw.

**Comment by troyengel** [comment]
Adding hopefully more impact data - server is Exchange 2016, using the latest of all the components with Arch: TB 45.7.0, Lightening 4.7.4. As per the others above, downgrading to 3.8.0 is working as expected again. Happy to provide debug if one of the devs shows us what's needed to help sort this out.

**Comment by mirthquake** [comment]
Same issue here. Cannot accept meeting invites.
Thunderbird 45.7.0 under Linux Mint 18.1
Lightning 4.7.4
Exchange EWS Provider 3.9.0 (final version)

**Comment by qrkourier** [comment]
+1
Thunderbird 45.7.0
Lightning 4.7.4
Exchange EWS Provider 3.9.0
Exchange server is Office365

If I launch Tbird from terminal and attempt to accept or decline a meeting invite this output appears:
````
Error: Couldn't find (UTC-05:00) Eastern Time (US & Canada)
9424f834-d565-4f18-9037-02440228f19f:https://outlook.office365.com/ews/exchange.asmx:jobObject.onRequestOk Error:TypeError: proposeStart.getInTimezone is not a function
````

**Comment by jonassundman** [comment]
It seems that by selecting "Edit the response before sending" in the confirmation popup and just accepting the responde without further editing, responses to invitations work.
Exchange EWS Provider 3.9.0 / Thunderbird 45.7.0 / Lightning 4.7.4

**Comment by default50** [comment]
@jonassundman confirmed that is a valid workaround, but it's not good if you want to decline an invite without sending out an email.

Ubuntu 16.04
Thunderbird 45.7.0
Lightning 4.7.7
Exchange EWS Provider 3.9.0

Rolling back to 3.8.0 solves it completely.

**Comment by ghost** [comment]
Looking at the changelog, it seems this was introduced by e9d219b0e09374d37ee597fae643ff6ab1ca4d9c

**Comment by troyengel** [comment]
@SvenMW following your breadcrumbs, I think it's here? (I'm making a guess)

* https://github.com/Ericsson/exchangecalendar/commit/e9d219b0e09374d37ee597fae643ff6ab1ca4d9c#diff-325a2ba8c3bc69abdc02c0a438aeb3d6R50

If you dig through upstream and try to trace it down, there's a comment right here that new code should be using 'calUtils.jsm' not .js:

* http://code.metager.de/source/xref/mozilla/thunderbird/calendar/base/modules/calUtils.jsm#4

The only place I can actually see it defined (and even this was hard to find, I don't understand Mozilla source code at all) was here:

* http://code.metager.de/source/xref/mozilla/thunderbird/calendar/base/backend/icaljs/calDateTime.js#79

Since the proposeStart and proposeEnd are explicitly calling cal.(), it seems that the way the commit is importing the resource doesn't get this guy added when using the .js? (I'm seriously just guessing here):

* http://doxygen.db48x.net/mozilla-full/html/d0/d83/interfacecalIDateTime.html

Maybe I'm completely wrong, but perhaps it'll provide the next person a breadcrumb...

**Comment by rainerklier** [comment]
"Edit the response before sending" workaround does not work for me:
openSUSE Tumbleweed x86_64
KDE Plasma 5.9.2
KDE Frameworks 5.31.0
Qt 5.7.1
Thunderbird 45.7.1
Lightning 4.7.7.1
Exchange EWS Provider 3.9.0

downgraded back to 3.8.0.
:-(

**Comment by ds2k5** [comment]
Manjaro Linux
Thunderbird: 45.7.1
Lightning 4.7.4
Exchange EWS Provider 3.9.0

How to STRIP the exchangecalendar.log  ?

Thanks

**Comment by DaMalo** [comment]
The "edit response" workaround seemed to work for me at first, but then I realized I was sending suggestions for different times in the response, even though I hadn't changed the original time in the form.
Switched back to 3.8.0 which works fine for me.

Ubuntu 16.04
Thunderbird 45.7.0
Lightning 4.7.4
Exchange EWS Provider 3.9.0

**Comment by ektosius** [comment]
Same problem here, reverted to 3.8.0, TB 45.7.1, Lightning 4.7.7.1, Exchange 2016, Windows 8.

I know about three ways to accept or decline an invite: 
* the invitation mail header
* the invite in the calendar view
* the status bar "invites:"

In my opinion in 3.8.0 the second version was the most reliable. First and last did not always work.

In 3.9.0 none of these work reliable. I was under the impression, that the first worked sometimes, but the client also sent confirms with changed (and nonsense) date and times.

**Comment by ydelau** [comment]
Hello, I confirm the issue on the following platform:

- Ubuntu 16.04
- Thunderbird 45.7
- Lightning 4.7.4
- Exchange EWS Provider 3.9.0

The only workaround is to rollback to EWS Provider 3.8.0 at the time.

**Comment by gwright83** [comment]
I can confirm the problem on the following platform:

- OS X El Capitan 10.11.6
- Thunderbird 45.8.0
- Lightning 4.7.8
- Exchange EWS Provider 3.9.0

Will try downgrading to EWS Provider 3.8.0 to see if that works.

**Comment by kstripp** [comment]
[didn't see this issue when I commented on #579. adding my comments here too]

Seems to be the same behavior that I started getting this week after our IT did a "service update". (They of course didn't specify anything more detailed than that)

- Debian Sid
- Thunderbird 45.8.0
- Lightning 4.7.8
- Exchange EWS Provider 3.9.0

A few other notes - all of the methods mentioned by @ektosius worked reliably for me using this configuration up until last week when IT did their update.

I can also confirm that 3.8.0 works for me.

**Comment by jamakal** [comment]
I am able to reproduce on:
Ubuntu 14.04
Thunderbird 45.8.0
Lightning 4.7.8
Exchange EWS Provider 3.9.0

Downgrading to 3.8.0 seems to resolve the problem.

**Comment by kiravi** [comment]
Confirm - is an issue in 3.9, Tbird-52.1.0 (32-bit)

**Comment by jameskephart** [comment]
Same here:  NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "proposeStart.getInTimezone is not a function"

Ubuntu 14.0.4 LTS
Lightning 5.4
EWS 3.9.0

**Comment by odecif** [comment]
Issue here as well

Linux Mint 17 (Cinnamon)
Thunderbird 52.2.1 (64-bit)
Lightning 5.4
EWS 3.9.0

**Comment by ghost** [comment]
This fork is not maintained, see here for a new version:
https://github.com/Ericsson/exchangecalendar/issues/610
https://github.com/ExchangeCalendar/exchangecalendar/

HTH

**Comment by warnertsf** [comment]
Same problem. In Thunderbird accepted appointments won't appear as accepted in Lightning, nor in MS Exchange! In MS Exchange accepted appointments though do appear as accepted in both.

Exchange calendar version: 3.9.0 
Lightning version: 5.4
Thunderbird version: 52.4.0 (64 bit)
Linux version: Ubuntu 16.04 (64 bit)

**Comment by warnertsf** [comment]
Same problem. In Thunderbird accepted appointments won't appear as accepted in Lightning, nor in MS Exchange! In MS Exchange accepted appointments though do appear as accepted in both.

Exchange calendar version: 3.9.0 
Lightning version: 5.4
Thunderbird version: 52.4.0 (64 bit)
Linux version: Ubuntu 16.04 (64 bit)

**Comment by ubuntuG** [comment]
Same problem. In Thunderbird accepted appointments won't appear as accepted in Lightning, nor in MS Exchange! In MS Exchange accepted appointments though do appear as accepted in both.

Exchange calendar version: 3.9.0 
Lightning version: 5.4
Thunderbird version: 52.4.0 (64 bit)
Linux version: Ubuntu 16.04 (64 bit)

**Comment by a6zj6** [comment]
Exchange calendar version: 3.9.0
Lightning version: 5.4
Thunderbird version: 52.5.2
Linux version: Ubuntu 14.04 LTS

I wasn't able to accept invites either - I click on Accept or Accept All and nothing happens. I had to roll back to 3.8.0 and this resolved the problem.

**Comment by smares** [comment]
Do you guys read the comments made? This is no longer maintained. Use the following fork: https://github.com/ExchangeCalendar/exchangecalendar/
